export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_CART = 'DELETE_CART';
export const ADD_ONE_CART = 'ADD_ONE_CART';
export const SUBTRACT_ONE_CART = 'SUBTRACT_ONE_CART';
export const BUY_SUCCESS = 'BUY_SUCCESS';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
